export const products = [
  {
    id: 1,
    title: "Asus ProArt GeForce RTX 4070",
    price: 999.99,
    category: "Graphic Cards",
    description: "Creator-grade RTX card with strong cooling and stable high-load performance.",
    image: "https://loremflickr.com/1200/800/asus,gpu?lock=1",
  },
  {
    id: 2,
    title: "MSI GeForce RTX 4060 Ti Ventus 2X",
    price: 299.99,
    category: "Graphic Cards",
    description: "Efficient dual-fan GPU for smooth 1080p and 1440p gaming.",
    image: "https://loremflickr.com/1200/800/msi,gpu?lock=2",
  },
  {
    id: 3,
    title: "Gigabyte RTX 4070 Windforce OC",
    price: 629.99,
    category: "Graphic Cards",
    description: "Balanced performance and thermals for modern games and creative software.",
    image: "https://loremflickr.com/1200/800/gigabyte,gpu?lock=3",
  },
  {
    id: 4,
    title: "ZOTAC RTX 3060 Twin Edge",
    price: 279.99,
    category: "Graphic Cards",
    description: "Compact RTX card with DLSS support and low-noise cooling.",
    image: "https://loremflickr.com/1200/800/nvidia,gpu?lock=4",
  },
  {
    id: 5,
    title: "Sapphire Pulse RX 6700 XT",
    price: 389.99,
    category: "Graphic Cards",
    description: "Solid AMD option for high FPS gaming at 1080p and 1440p.",
    image: "https://loremflickr.com/1200/800/amd,gpu?lock=5",
  },
  {
    id: 6,
    title: "ASRock RX 7600 Challenger",
    price: 269.99,
    category: "Graphic Cards",
    description: "Budget-friendly modern GPU with reliable cooling design.",
    image: "https://loremflickr.com/1200/800/gpu,pc?lock=6",
  },
  {
    id: 7,
    title: "LG UltraGear 27-inch QHD 165Hz",
    price: 349.99,
    category: "Monitors",
    description: "Fast IPS gaming monitor with crisp colors and high refresh rate.",
    image: "https://loremflickr.com/1200/800/gaming,monitor?lock=7",
  },
  {
    id: 8,
    title: "Dell 24-inch FHD IPS Monitor",
    price: 169.99,
    category: "Monitors",
    description: "Clean design office monitor with accurate colors and eye comfort.",
    image: "https://loremflickr.com/1200/800/dell,monitor?lock=8",
  },
  {
    id: 9,
    title: "Samsung Odyssey G5 32-inch",
    price: 329.99,
    category: "Monitors",
    description: "Curved QHD display for immersive gaming and multitasking.",
    image: "https://loremflickr.com/1200/800/samsung,monitor?lock=9",
  },
  {
    id: 10,
    title: "AOC 24G2 144Hz Gaming Monitor",
    price: 189.99,
    category: "Monitors",
    description: "Popular 144Hz monitor with smooth visuals and thin bezels.",
    image: "https://loremflickr.com/1200/800/aoc,monitor?lock=10",
  },
  {
    id: 11,
    title: "MSI Modern MD241P",
    price: 219.99,
    category: "Monitors",
    description: "Minimal monitor with ergonomic stand and vivid IPS panel.",
    image: "https://loremflickr.com/1200/800/office,monitor?lock=11",
  },
  {
    id: 12,
    title: "ASUS TUF VG249Q1A",
    price: 199.99,
    category: "Monitors",
    description: "Responsive gaming monitor built for low latency play.",
    image: "https://loremflickr.com/1200/800/asus,monitor?lock=12",
  },
  {
    id: 13,
    title: "Logitech G102 Light Sync Mouse",
    price: 29.99,
    category: "Mouse",
    description: "Accurate entry-level gaming mouse with RGB lighting.",
    image: "https://loremflickr.com/1200/800/logitech,mouse?lock=13",
  },
  {
    id: 14,
    title: "Razer DeathAdder Essential",
    price: 39.99,
    category: "Mouse",
    description: "Ergonomic shape and reliable sensor for long sessions.",
    image: "https://loremflickr.com/1200/800/razer,mouse?lock=14",
  },
  {
    id: 15,
    title: "SteelSeries Rival 3",
    price: 34.99,
    category: "Mouse",
    description: "Lightweight performance mouse with durable switches.",
    image: "https://loremflickr.com/1200/800/gaming,mouse?lock=15",
  },
  {
    id: 16,
    title: "Corsair Harpoon RGB Pro",
    price: 44.99,
    category: "Mouse",
    description: "Fast tracking gaming mouse with textured side grips.",
    image: "https://loremflickr.com/1200/800/corsair,mouse?lock=16",
  },
  {
    id: 17,
    title: "Glorious Model O",
    price: 59.99,
    category: "Mouse",
    description: "Ultra-light honeycomb design for quick flicks and control.",
    image: "https://loremflickr.com/1200/800/pc,mouse?lock=17",
  },
  {
    id: 18,
    title: "HyperX Pulsefire Haste",
    price: 49.99,
    category: "Mouse",
    description: "Featherweight competitive mouse with flexible cable.",
    image: "https://loremflickr.com/1200/800/hyperx,mouse?lock=18",
  },
  {
    id: 19,
    title: "Redragon K552 Mechanical Keyboard",
    price: 54.99,
    category: "Keyboard",
    description: "Compact mechanical keyboard with tactile switch feel.",
    image: "https://loremflickr.com/1200/800/mechanical,keyboard?lock=19",
  },
  {
    id: 20,
    title: "Corsair K70 RGB Pro",
    price: 149.99,
    category: "Keyboard",
    description: "Premium full-size keyboard built for fast response.",
    image: "https://loremflickr.com/1200/800/corsair,keyboard?lock=20",
  },
  {
    id: 21,
    title: "Razer BlackWidow V3",
    price: 129.99,
    category: "Keyboard",
    description: "Clicky mechanical keyboard with bright RGB effects.",
    image: "https://loremflickr.com/1200/800/razer,keyboard?lock=21",
  },
  {
    id: 22,
    title: "Logitech G413 SE",
    price: 89.99,
    category: "Keyboard",
    description: "Durable aluminum-frame keyboard with dependable switches.",
    image: "https://loremflickr.com/1200/800/logitech,keyboard?lock=22",
  },
  {
    id: 23,
    title: "Keychron K2 Wireless",
    price: 99.99,
    category: "Keyboard",
    description: "Popular wireless mechanical keyboard for work and gaming.",
    image: "https://loremflickr.com/1200/800/wireless,keyboard?lock=23",
  },
  {
    id: 24,
    title: "Fantech Maxfit67",
    price: 79.99,
    category: "Keyboard",
    description: "Compact 65% keyboard with hot-swappable switch support.",
    image: "https://loremflickr.com/1200/800/rgb,keyboard?lock=24",
  },
  {
    id: 25,
    title: "HyperX Cloud II Gaming Headset",
    price: 89.99,
    category: "Headset",
    description: "Comfortable headset with clean mic voice pickup.",
    image: "https://loremflickr.com/1200/800/gaming,headset?lock=25",
  },
  {
    id: 26,
    title: "SteelSeries Arctis 5 RGB",
    price: 99.99,
    category: "Headset",
    description: "Detailed spatial audio with breathable ear cushions.",
    image: "https://loremflickr.com/1200/800/steelseries,headset?lock=26",
  },
  {
    id: 27,
    title: "Razer Kraken X",
    price: 59.99,
    category: "Headset",
    description: "Lightweight wired headset with virtual surround sound.",
    image: "https://loremflickr.com/1200/800/razer,headset?lock=27",
  },
  {
    id: 28,
    title: "Logitech G435 Lightspeed",
    price: 69.99,
    category: "Headset",
    description: "Wireless headset with low-latency connectivity.",
    image: "https://loremflickr.com/1200/800/logitech,headphones?lock=28",
  },
  {
    id: 29,
    title: "Corsair HS55 Stereo",
    price: 64.99,
    category: "Headset",
    description: "Soft memory foam cushions and clear flip-to-mute mic.",
    image: "https://loremflickr.com/1200/800/corsair,headset?lock=29",
  },
  {
    id: 30,
    title: "JBL Quantum 100",
    price: 49.99,
    category: "Headset",
    description: "Budget gaming headset with punchy sound profile.",
    image: "https://loremflickr.com/1200/800/jbl,headset?lock=30",
  },
];

export default products;


